{
 "title": "Docker Container Basic Metrics",
 "tags": [
  "docker",
  "cadvisor"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU Usage (per container)",
   "type": "graph",
   "yaxes": [
    { "format": "percent", "label": "CPU" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total[1m]) * 100",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Memory Usage (per container)",
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    { "expr": "container_memory_usage_bytes", "legendFormat": "{{ container }}" }
   ]
  },
  {
   "title": "Network I/O (per container)",
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bytes", "label": "Network" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total[1m])",
     "legendFormat": "{{ container }} (recv)"
    },
    {
     "expr": "rate(container_network_transmit_bytes_total{container!=\"\"}[1m])",
     "legendFormat": "{{ container }} (sent)"
    }
   ]
  },
  {
   "title": "Disk I/O (per container)",
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes", "label": "Disk I/O" }
   ],
   "targets": [
    {
     "expr": "rate(container_fs_reads_bytes_total[1m])",
     "legendFormat": "{{ container }} (read)"
    },
    {
     "expr": "rate(container_fs_writes_bytes_total{container!=\"\"}[1m])",
     "legendFormat": "{{ container }} (write)"
    }
   ]
  }
 ]
}